# Generated by Django 5.2.15 on 2026-06-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_latitude_gym_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='openstreetmap', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('query', models.TextField(blank=True)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('total_updated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_claimed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gym',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gyms', to='gyms.importbatch'),
        ),
    ]
