# Generated by Django 5.2.15 on 2026-06-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_latitude_gym_longitude'),
        ('gyms', '0004_merge_photo_and_import_migrations'),
    ]

    operations = [
    ]
