import html
import random
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils.text import slugify

from apps.gyms.models import Gym, GymImage


PALETTES = [
    ('#101010', '#2f7cff', '#ffffff'),
    ('#13151a', '#6ee7b7', '#ffffff'),
    ('#17111f', '#f97316', '#ffffff'),
    ('#111827', '#a78bfa', '#ffffff'),
    ('#0f172a', '#f43f5e', '#ffffff'),
]


class Command(BaseCommand):
    help = 'Generate local SVG cover images for gyms that do not have photos yet. Useful for imported/test data.'

    def add_arguments(self, parser):
        parser.add_argument('--source', default='', help='Only process gyms with this import source, e.g. geoapify.')
        parser.add_argument('--city', default='', help='Only process gyms in this city.')
        parser.add_argument('--limit', type=int, default=0, help='Maximum gyms to process. 0 means no limit.')
        parser.add_argument('--replace', action='store_true', help='Replace existing placeholder images created by this command.')
        parser.add_argument('--approve-only', action='store_true', help='Only process APPROVED gyms.')
        parser.add_argument('--dry-run', action='store_true', help='Show what would be generated without writing files/database rows.')

    def handle(self, *args, **options):
        qs = Gym.objects.all().order_by('id')
        if options['source']:
            qs = qs.filter(source=options['source'])
        if options['city']:
            qs = qs.filter(city__iexact=options['city'])
        if options['approve_only']:
            qs = qs.filter(status=Gym.Status.APPROVED)

        if not options['replace']:
            qs = qs.filter(images__isnull=True)
        else:
            qs = qs.distinct()

        limit = options['limit']
        gyms = list(qs[:limit] if limit and limit > 0 else qs)
        if not gyms:
            self.stdout.write(self.style.WARNING('No gyms matched, or all matched gyms already have photos.'))
            return

        media_root = Path(settings.MEDIA_ROOT or 'media')
        output_dir = media_root / 'gyms' / 'generated'
        rel_dir = Path('gyms') / 'generated'

        if options['dry_run']:
            for gym in gyms[:30]:
                self.stdout.write(f'DRY: would generate cover for #{gym.id} {gym.name}')
            self.stdout.write(self.style.SUCCESS(f'Dry run complete: {len(gyms)} gym(s) matched.'))
            return

        output_dir.mkdir(parents=True, exist_ok=True)
        created = 0
        replaced = 0
        with transaction.atomic():
            for gym in gyms:
                if options['replace']:
                    old_placeholders = gym.images.filter(source='placeholder')
                    replaced += old_placeholders.count()
                    old_placeholders.delete()

                filename = f'{gym.id}-{slugify(gym.name)[:60] or "gym"}.svg'
                absolute_path = output_dir / filename
                relative_path = rel_dir / filename
                absolute_path.write_text(self._svg_for_gym(gym), encoding='utf-8')

                GymImage.objects.create(
                    gym=gym,
                    image=str(relative_path).replace('\\', '/'),
                    source='placeholder',
                    credit='Generated by myGym placeholder command',
                    alt_text=f'{gym.name} cover image',
                    is_cover=not gym.images.exclude(source='placeholder').exists(),
                )
                created += 1

        self.stdout.write(self.style.SUCCESS(f'Generated {created} placeholder photo(s). Replaced {replaced}.'))

    def _svg_for_gym(self, gym):
        seed = gym.id or sum(ord(c) for c in gym.name)
        random.seed(seed)
        bg, accent, fg = random.choice(PALETTES)
        initial = html.escape((gym.name[:1] or 'G').upper())
        name = html.escape(gym.name)
        city = html.escape(gym.city or 'myGym')
        return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="900" viewBox="0 0 1400 900" role="img" aria-label="{name}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{bg}"/>
      <stop offset="1" stop-color="{accent}"/>
    </linearGradient>
    <filter id="blur"><feGaussianBlur stdDeviation="45"/></filter>
  </defs>
  <rect width="1400" height="900" fill="url(#g)"/>
  <circle cx="1120" cy="180" r="230" fill="#ffffff" opacity=".13" filter="url(#blur)"/>
  <circle cx="230" cy="760" r="280" fill="#ffffff" opacity=".08" filter="url(#blur)"/>
  <rect x="90" y="90" width="1220" height="720" rx="56" fill="#ffffff" opacity=".10" stroke="#ffffff" stroke-opacity=".22"/>
  <text x="130" y="235" fill="{fg}" opacity=".82" font-family="Inter, Arial, sans-serif" font-size="34" font-weight="700">myGym · {city}</text>
  <text x="130" y="470" fill="{fg}" font-family="Inter, Arial, sans-serif" font-size="132" font-weight="900">{initial}</text>
  <text x="130" y="590" fill="{fg}" font-family="Inter, Arial, sans-serif" font-size="58" font-weight="900">{name}</text>
  <text x="130" y="670" fill="{fg}" opacity=".82" font-family="Inter, Arial, sans-serif" font-size="32" font-weight="600">Fitness · Training · Wellness</text>
  <g transform="translate(1010 575)" opacity=".88">
    <rect x="0" y="50" width="260" height="34" rx="17" fill="{fg}"/>
    <circle cx="-35" cy="67" r="54" fill="none" stroke="{fg}" stroke-width="28"/>
    <circle cx="295" cy="67" r="54" fill="none" stroke="{fg}" stroke-width="28"/>
  </g>
</svg>
'''
