# Generated by Django 5.2.15 on 2026-06-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='systemlogs__level_4aa8e2_idx',
            old_name='systemlogs_level_c_3152b5_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='systemlogs__created_c35c47_idx',
            old_name='systemlogs_created_c58330_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='systemlogs__event_86d247_idx',
            old_name='systemlogs_event_6b2b5f_idx',
        ),
    ]
